export const ActionTypes = {
  SET_LOADING: "SET_LOADING",
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_ERROR: "SET_ERROR",
  ADD_TO_BASET: "ADD_TO_BASKET",
  REMOVE_ITEM: "REMOVE_ITEM",
  UPDATE_ITEM: "UPDATE_ITEM",
  SET_BASKET: "SET_BASKET",
  SET_BASKET_LOADING: "SET_BASKET_LOADING",
  SET_BASKET_ERROR: "SET_BASKET_ERROR",
  DECREASE_ITEM: "DECREASE_ITEM",
};
